name: Test

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pre dependencies
        run: yarn global add ionic@4.x cordova@8.x
      - name: Install
        run: npm rebuild node-sass && yarn install --frozen-lockfile
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build -- --prod

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pre dependencies
        run: yarn global add ionic@4.x cordova@8.x
      - name: Install
        run: npm rebuild node-sass && yarn install --frozen-lockfile
      - name: Test
        run: npm run test:e2e
      - name: Build
        run: npm run build -- --prod
